# Generated by Django 5.2.5 on 2025-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics/'),
        ),
    ]
