# Generated by Django 5.2.5 on 2025-10-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_cover_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cover_pic',
            new_name='cover_picture',
        ),
    ]
