# Generated by Django 5.2.7 on 2025-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_icon',
            field=models.ImageField(blank=True, null=True, upload_to='group_icons/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
