# Generated by Django 5.2.7 on 2025-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_chat_type_conversation_group_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=10),
        ),
    ]
