# Generated by Django 5.2.7 on 2025-11-25 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_chat_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Private Chat'), ('group', 'Group Chat')], default='private', max_length=10),
        ),
    ]
