# Generated by Django 4.2 on 2026-02-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_comment_options_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['to_user', '-created_at'], name='homepage_no_to_user_b9b8c0_idx'),
        ),
    ]
