# Generated by Django 4.2 on 2026-02-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_notification_homepage_no_to_user_b9b8c0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bg_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='font_style',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
