# Generated by Django 4.2 on 2026-02-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_post_image_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
