# Generated by Django 4.2 on 2026-02-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_post_image_remove_post_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
