"""
Django settings for MyApp project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ruof!k^iprw38&30(sk&snd3$^8(7r%)fr(x*7!$ltv40wz$jj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
                "127.0.0.1", 
                "localhost",
                "0.0.0.0", 
                ".ngrok-free.dev",
                #"django_channels_app"
                ".trycloudflare.com",
                "samacharapp.onrender.com",
                "samacharapp.in",
                "www.samacharapp.in",
                'samacharapp-qj9a.onrender.com',
                ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'homepage.apps.HomepageConfig',                           # ✅ your renamed app
    'profiles.apps.ProfilesConfig',
    #'homepage', 
    'channels',
    'chat',
    'rest_framework',
    'reels',
    'status',
    
    

]

#WSGI_APPLICATION = 'MyApp.wsgi.application'
ASGI_APPLICATION = 'MyApp.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],   # Redis from Docker
        },
    },
}
"""
WSGI_APPLICATION = 'MyApp.wsgi.application'
ASGI_APPLICATION = 'MyApp.asgi.application'
if DEBUG:
        CHANNEL_LAYERS = {
            "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:

    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
            #'hosts': [('127.0.0.1', 6380)],
                "hosts": [("redis", 6379)],

        },
    },
}

"""

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    
]
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 
                        'http://localhost:8000',
                        "http://django_channels_app:8000",
                        "https://*.trycloudflare.com",
                        "https://*.ngrok-free.dev", 
                        " https://subdepartmental-loudly-miles.ngrok-free.dev"                       
                        ]

ROOT_URLCONF = 'MyApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                

            ],
        },
    },
]
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/homepage/'
LOGOUT_REDIRECT_URL = '/login/'



WSGI_APPLICATION = 'MyApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.postgresql',
  #      'NAME': os.environ.get('Myappdb'),          # same name as in pgAdmin
   #     'USER': os.environ.get('postgres'),         # your PostgreSQL username
    #    'PASSWORD': os.environ.get('Mani2405@'), # your PostgreSQL password
     #   'HOST': 'localhost',
      #  'PORT': '5432',
    #}
#}
def is_docker_environment():
    hostname = socket.gethostname()
    try:
        socket.gethostbyname('db')
        return True
    except socket.error:
        return False

DB_HOST = 'db' if is_docker_environment() else 'localhost'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}
     
      


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'
#STATICFILES_DIRS = [BASE_DIR / 'static']   # cover image

# ---------- STATIC FILES ----------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ---------- MEDIA FILES ----------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =====================
# SESSION FIX (VERY IMPORTANT)
# =====================
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False  # because you are using http://localhost
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = "Lax"




